### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Exquitas** [BeerK0in/generator-gunbot#28]
Hi i'm getting the following error when starting ginit:

```
/home/root/.nvm/versions/node/v6.11.2/lib/node_modules/yo/node_modules/configstore/index.js:53
				throw err;
				^

Error: EACCES: permission denied, open '/home/root/.config/configstore/insight-yo.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.get (/home/root/.nvm/versions/node/v6.11.2/lib/node_modules/yo/node_modules/configstore/index.js:34:26)
    at Object.Configstore (/home/root/.nvm/versions/node/v6.11.2/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/home/root/.nvm/versions/node/v6.11.2/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/home/root/.nvm/versions/node/v6.11.2/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

```

**Comment by BeerK0in** [comment]
Try running ginit as root user.
